
import Sidebar from "@/components/Shared/Sidebar/Sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "build tech",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <div>
            <Sidebar />
            {children}
        </div>
    );
}
